/// <reference path="jquery.d.ts" />
/// <reference path="../Parsect/src/parsect.ts" />
/// <reference path="../Parsect/src/globals.ts" />
/// <reference path="../Parsect/src/type.ts" />
/// <reference path="../Parsect/src/parser.ts" />

var genButton = <any>$("#gen");
var textarea = <any>$("#source");
var docs = <any>$("#docs");

textarea.val("");

var documentContent:JQuery;
var cssText:string;

function generateDocuments(){
	docs.children().remove();
	docs.append("<p>Document generating...</p>");
	
	setTimeout(()=>{
		var sourceCode = textarea.val();
		var result = DTSDoc.program.parse(new Source(sourceCode, 0));
		var members:DTSDoc.TSModuleMember[] = result.value;
		//docs.innerText = members;
		//$(docs).append(members.join());
		documentContent = $('<div/>');
		documentContent.append(members.map((m)=>m.toHTML()));

		docs.children().remove();
		docs.append(documentContent);
	}, 1);
}

genButton.click(()=>{
	generateDocuments();
});

$.ajax("sample2.d.ts", {
	contentType: "text/plain",
	dataType: "text",
	success: (data)=>{
		textarea.val(data);
		generateDocuments();
	}
});
$.ajax("style.css", {
	contentType: "text/plain",
	dataType: "text",
	success: (data)=>{
		cssText = data;
	}
});


$('#download').click(()=>{
	if(documentContent){
		var source = encodeURIComponent(documentContent.html());

		source = "<body>" + source + "<footer>generated by <a>DTSDoc</a></footer></body>";
		source = '<html><head><style>' + cssText + '</style></head>' + source + "</html>";

		$('#downloadLink').attr('href', "data:text/html," + source);
	}
});